Remove unused variable
causalize/vector/causalization_algorithm.cpp: In member function 'bool Causalize::CausalizationStrategyVector::Causalize()':
causalize/vector/causalization_algorithm.cpp:106:35: error: unused variable 'numAcausalEqs' [-Werror=unused-variable]
     list<VectorVertex>::size_type numAcausalEqs = equationDescriptors.size();